// <auto-generated />
using System;
using LogisticBackend.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogisticBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogisticBackend.Data.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExperienceStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperienceStart = new DateTime(2015, 5, 9, 21, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Иванов Иван Иванович",
                            IsActive = true,
                            Phone = "+375291234567"
                        },
                        new
                        {
                            Id = 2,
                            ExperienceStart = new DateTime(2018, 3, 21, 21, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Петров Петр Петрович",
                            IsActive = true,
                            Phone = "+375441234567"
                        });
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("MileageAtExpense")
                        .HasColumnType("real");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 350m,
                            Date = new DateTime(2024, 1, 9, 21, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Замена масла",
                            MileageAtExpense = 150500f,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            Date = new DateTime(2024, 1, 14, 21, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Техническое обслуживание",
                            MileageAtExpense = 121000f,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.FuelTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<float>("Liters")
                        .HasColumnType("real");

                    b.Property<decimal>("PricePerLiter")
                        .HasColumnType("numeric");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("FuelTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 1, 11, 21, 0, 0, 0, DateTimeKind.Utc),
                            DriverId = 1,
                            Liters = 150f,
                            PricePerLiter = 2.1m,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 1, 19, 21, 0, 0, 0, DateTimeKind.Utc),
                            DriverId = 2,
                            Liters = 180f,
                            PricePerLiter = 2.05m,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<float>("IntervalMileage")
                        .HasColumnType("real");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceCompany")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Maintenances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 800m,
                            Date = new DateTime(2024, 2, 4, 21, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ТО-2",
                            IntervalMileage = 15000f,
                            IsCompleted = true,
                            Mileage = 151000,
                            ServiceCompany = "ТехСервис",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 600m,
                            Date = new DateTime(2024, 2, 9, 21, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ТО-1",
                            IntervalMileage = 20000f,
                            IsCompleted = true,
                            Mileage = 121500,
                            ServiceCompany = "АвтоМастер",
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CargoDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("CargoWeight")
                        .HasColumnType("real");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EndMileage")
                        .HasColumnType("integer");

                    b.Property<float?>("FuelSpent")
                        .HasColumnType("real");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartMileage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("TripTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoDescription = "Молочная продукция",
                            CargoWeight = 5000f,
                            DriverId = 1,
                            Notes = "Без происшествий",
                            Number = "TRIP-001",
                            Route = "Минск — Брест",
                            StartDateTime = new DateTime(2025, 12, 3, 5, 0, 0, 0, DateTimeKind.Utc),
                            StartMileage = 150000,
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CargoDescription = "Мясная продукция",
                            CargoWeight = 3000f,
                            DriverId = 2,
                            EndDateTime = new DateTime(2024, 1, 7, 19, 0, 0, 0, DateTimeKind.Utc),
                            EndMileage = 120380,
                            FuelSpent = 90f,
                            Notes = "",
                            Number = "TRIP-002",
                            Route = "Минск — Гродно",
                            StartDateTime = new DateTime(2024, 1, 7, 4, 0, 0, 0, DateTimeKind.Utc),
                            StartMileage = 120000,
                            Status = 3,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentBookValue")
                        .HasColumnType("numeric");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InitialCost")
                        .HasColumnType("numeric");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Mileage")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Volvo",
                            CurrentBookValue = 70000m,
                            FuelType = "Diesel",
                            InitialCost = 90000m,
                            InventoryNumber = "INV-001",
                            LicensePlate = "1234 AB-7",
                            Mileage = 150000f,
                            Model = "FH16",
                            Status = 1,
                            VIN = "VIN00000000000001",
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Scania",
                            CurrentBookValue = 85000m,
                            FuelType = "Diesel",
                            InitialCost = 105000m,
                            InventoryNumber = "INV-002",
                            LicensePlate = "5678 AC-7",
                            Mileage = 120000f,
                            Model = "R500",
                            Status = 2,
                            VIN = "VIN00000000000002",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Expense", b =>
                {
                    b.HasOne("LogisticBackend.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Expenses")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.FuelTransaction", b =>
                {
                    b.HasOne("LogisticBackend.Data.Entities.Driver", "Driver")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("LogisticBackend.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("FuelTransactions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Maintenance", b =>
                {
                    b.HasOne("LogisticBackend.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Maintenances")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Trip", b =>
                {
                    b.HasOne("LogisticBackend.Data.Entities.Driver", "Driver")
                        .WithMany("Trips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogisticBackend.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Driver", b =>
                {
                    b.Navigation("FuelTransactions");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("LogisticBackend.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("FuelTransactions");

                    b.Navigation("Maintenances");

                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
